### ISSUE TITLE
Review My App

### ISSUE THREAD

**Issue by bluyam** [bluyam/twitter#1]
My app is complete! :+1: Please review /cc @codepathreview. :smiley:

**Comment by minhchau273** [comment]
Hi Kyle,
I cannot view the timeline after logging in. Could you please take a look and update this?

![twitter](https://cloud.githubusercontent.com/assets/12395213/13057278/9973f83c-d44d-11e5-8001-216c54c7e0e8.gif)

Thanks.

**Comment by bluyam** [comment]
Hi Chau,

It looks like the app that you're redirected to after login is not mine - I
have different buttons than the resulting screen. My suspicion is that you
have another Twitter app installed on your simulator that has the same
redirect as mine after the sign in is completed (I just used
cptwitterdemo://, but I can change this if you'd like.) Anyway, I believe
it will work if you delete the other submissions on your simulator. Would
you like me to change the redirection as well?

Thanks,
Kyle

**Comment by minhchau273** [comment]
Okay, I run your app on another simulator and it works fine :D

**Comment by minhchau273** [comment]
:+1: Fantastic job with the submission! The point of this homework was to explore an example of a full MVC application with a RESTful API. 

### Some small comments:
- Note that you should resolve all the Auto Layout constraint errors in your nibs.
- The auto layout may not work well.

<img width="373" alt="screen shot 2016-02-16 at 1 54 28 am" src="https://cloud.githubusercontent.com/assets/12395213/13057678/5ac5c1f8-d450-11e5-85d3-bd9d4d0f0672.png">
- Nice work setting up the controls within the Tweet cells. It can sometimes be hard to have a clean design for embedded controls because it usually involves cumbersome plumbing. This is an instance where I think having the model handle the network action helps greatly simplify the implementation.
- Your app crashes when I view my profile. :confused: 
  <img width="757" alt="screen shot 2016-02-16 at 1 57 46 am" src="https://cloud.githubusercontent.com/assets/12395213/13057771/ec41878e-d450-11e5-929a-bb747e92d348.png">
- Good job implementing `compose new tweet` feature. But after tweeting then back to the timeline, this new tweet should be appear immediately without refresh. You should try implementing the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience. But don't worried, this is the feature in the next assignment :smile:
- Great work with formatting timestamp and abbreviating count number. :star2: 

Excellent submission overal :tada: 

We have a detailed [Project 4 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_4_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

**Comment by bluyam** [comment]
Thanks Chau! :smile: my profile view is still in the progress of being implemented, so that may be why it wasn't working so well :disappointed:
