### ISSUE TITLE
Review My App

### ISSUE THREAD

**Issue by bluyam** [bluyam/twitter#2]
My app is complete, please review /cc @codepathreview :smile:

**Comment by minhchau273** [comment]
Hi Kyle,

I do not see an animated gif in your README. Please add a gif ASAP. Once you have added your gif, make sure that it actually renders (animates) within your README.

Your assignment needs to be updated within 24hrs in order for you to receive credit for this assignment.

Thanks,
Chau

**Comment by bluyam** [comment]
@minhchau273 
I'm really sorry - I just saw your response now. I will get right on the gif! :+1:

**Comment by bluyam** [comment]
@minhchau273 got it!

**Comment by minhchau273** [comment]
:+1: Great work! We added this homework so that you'll have the experience building an app that's more similar in complexity to a production app. The optional account switching feature is interesting because you have to think about how TwitterClient is caching the access token to make sure it works correctly for multiple accounts.

### Some small comments:
- Nice job with using `UITapGestureRecognizer` to perform the segue.
- You should try implementing the post tweet insertion into the feed. In real MVC apps, the more polished experiences have to do a certain amount of local object management to make a fully seamless experience.
- Note that you should resolve all the Auto Layout constraint warnings in your nibs.

We have a detailed [Project 5 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_5_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
